name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure all history and tags are fetched

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Downcase REPO
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

    - name: Use REPO
      run: |
        echo "The value of REPO is: ${REPO}"

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Lower Case Owner Name
      run: |
        echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
      env:
        OWNER: ${{ github.repository_owner }}

    - name: Get Version and Create .meta File
      run: |
        echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
        echo "BUILD=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

        echo "CISO_ASSISTANT_VERSION=$(git describe --tags --always)" > .meta
        echo "CISO_ASSISTANT_BUILD=$(git rev-parse --short HEAD)" >> .meta

        cp .meta ./backend/
        cp .meta ./backend/ciso_assistant/

    - name: List Backend Directory Contents
      run: ls -la ./backend

    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/backend:${{ env.VERSION }}
          ghcr.io/${{ github.repository }}/backend:latest
        platforms: linux/amd64,linux/arm64,linux/arm64/v8

    - name: List Frontend Directory Contents
      run: ls -la ./frontend

    - name: Build and Push Frontend Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/frontend:${{ env.VERSION }}
          ghcr.io/${{ github.repository }}/frontend:latest
        platforms: linux/amd64,linux/arm64,linux/arm64/v8
